### ISSUE TITLE
CASTLES.PAS is broken

### ISSUE THREAD

**Issue by mmoya** [merchise/fortaleza#3]
The file `CASTLES.PAS` is corrupted. There are rubbish starting from line 795. Maybe @rsotolongo, who provided a missing file, can check if he has a correct copy.

**Comment by rsotolongo** [comment]
Sure, I have it. Please check the attached file.
[CASTLES.PAS.zip](https://github.com/merchise/fortaleza/files/3905885/CASTLES.PAS.zip)
