### ISSUE TITLE
WIN.ASM is broken

### ISSUE THREAD

**Issue by mmoya** [merchise/fortaleza#5]
The file `WIN.ASM` is corrupted. There are rubbish starting from line [127](https://github.com/merchise/fortaleza/blob/master/WIN.ASM#L127). Maybe @rsotolongo has a correct copy.

(see #2)

**Comment by rsotolongo** [comment]
@mmoya I uploaded my local version of WIN.ASM into a new branch, please verify it and let's approve the PR in case it is OK.

**Comment by mmoya** [comment]
Fixed by #6.
